### ISSUE TITLE
Error message on Update Problems

### ISSUE THREAD

**Issue by anandology** [pipalacademy/engage#5]
After adding a problem repository and updating the problems, the following error is shown. 

<img width="576" alt="Screenshot 2022-06-08 at 12 11 32 PM" src="https://user-images.githubusercontent.com/7569/172549292-30fe3e22-5b40-4d54-aa58-779df320db35.png">

## Expected Outcome

No error should be shown.

## How to reproduce

1. create a new git repo with a sample problem
2. add a new problem repository with that git repo
3. click on "update problems " action on the problem repository page
4. you'll see the error message

**Comment by nikochiko** [comment]
This is a side-effect of this try-except block:
https://github.com/pipalacademy/engage/blob/df9ff87f3f4cb42376d43bb9181ba52b3c0d5253/engage/engage/doctype/problem_repository/problem_repository.py#L74-L81

It shouldn't affect the behavior of the program. I'll patch this with a fix that uses `frappe.db.exists()` instead of this try-except.
