### ISSUE TITLE
review page problem is not visible

### ISSUE THREAD

**Issue by vikipedia** [pipalacademy/engage#52]
if I am reviewing some submission, on that page it would be good to have problem description visible

**Comment by anandology** [comment]
we could do that as a separate tab along with the solution.

**Comment by nikochiko** [comment]
we should work on a mock-up for this.
exercism has a link to the exercise page for this, rather than directly adding the description here. we need not do the same, but i think it would also be useful to be able to spin up an editor with the solution code and then try out different cases to see why something isn't working.

**Comment by nikochiko** [comment]
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/37668193/179731402-3009460c-eb23-46d0-8621-60c65492fe6b.png">

This is what I iterated to. Mostly stock frappe/bootstrap with a few changes, my deviations from this didn't look very good.
I think we can also add a tab for the test results. I have left some todo comments for it.
